- name: Initial setup CT
  hosts: proxmox
  vars_files:
    - config.yml
    - cts.yml
  tasks:
    - name: Create container for PVE
      community.general.proxmox:
        vmid: "{{ item.value.vmid }}"
        node: "{{ node }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        password: "{{ item.value.password }}"
        hostname: "{{ item.value.hostname }}"
        cores: "{{ item.value.cores }}"
        memory: "{{ item.value.memory }}"
        swap: "{{ item.value.swap }}"
        disk: "{{ item.value.disk }}"
        storage: "{{ item.value.storage }}"
        unprivileged: "{{ item.value.unprivileged }}"
        description: "{{ item.value.description }}"
        ostemplate: "{{ item.value.ostemplate }}"
        proxmox_default_behavior: "{{ proxmox_default_behavior }}"
        onboot: "{{ item.value.onboot }}"
        netif: "{{ item.value.netif }}"
        features: "{{ item.value.features }}"
      loop: "{{ lookup('dict', cts) }}"
      tags:
      - create

    - name: Start container for PVE
      community.general.proxmox:
        vmid: "{{ item.value.vmid }}"
        node: "{{ node }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        proxmox_default_behavior: "{{ proxmox_default_behavior }}"
        state: started
      loop: "{{ lookup('dict', cts) }}"
      tags:
      - start